
DELETE FROM Advertisements;
INSERT INTO Advertisements ("id", "link") VALUES (1, 'Content/Images/ads/ad_image1.png');
INSERT INTO Advertisements ("id", "link") VALUES (2, 'Content/Images/ads/ad_image2.jpg');

DELETE FROM Archives;
INSERT INTO Archives ("id", "title", "link") VALUES (1, 'Summer 2015 newsletter', 'Content/Archives/DPNA_Newsletter_Summer_2015.pdf');
INSERT INTO Archives ("id", "title", "link") VALUES (2, 'Fall 2015 newsletter', 'Content/Archives/DPNA_Newsletter_Fall_2015.pdf');
INSERT INTO Archives ("id", "title", "link") VALUES (3, 'Winter 2015 newsletter', 'Content/Archives/DPNA_Newsletter_Winter_2015.pdf');
INSERT INTO Archives ("id", "title", "link") VALUES (4, 'Spring 2016 newsletter', 'Content/Archives/DPNA_Newsletter_Spring_2016.pdf');

DELETE FROM Articles;
INSERT INTO Articles ("id", "uuid", "hfso", "title", "image", "text") VALUES (1, '4a60c1a5-036f-4ea9-b94c-4d72be6d3aa2', 'T', 'People Article', 'Content/Images/articles/people1.jpg', 'People article lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec elit libero, tincidunt sit amet placerat non, finibus vitae orci. Aliquam felis arcu, mattis in volutpat sit amet, volutpat a diam. Pellentesque pharetra nisl luctus purus venenatis tempor ut vitae magna. Donec ac tellus libero. Morbi ultricies arcu nec pretium maximus. Vivamus congue dolor sed libero lobortis, in ullamcorper elit vestibulum. Aenean pellentesque est non elementum vehicula. Vivamus ac lectus dolor. Integer risus arcu, sollicitudin sed vulputate nec, molestie eu odio. Quisque quam diam, viverra non leo eu, mattis semper ante. Duis sed lectus fermentum, dignissim turpis ut, feugiat elit. Vivamus sit amet neque risus.');
INSERT INTO Articles ("id", "uuid", "hfso", "title", "image", "text") VALUES (2, '411a0890-723c-4fb0-b574-82aef5e1b64a', 'T', 'Nature Article', 'Content/Images/articles/nature1.jpg', 'Nature article phasellus commodo tortor a imperdiet volutpat. Nam dapibus sodales velit eget accumsan. Etiam accumsan rhoncus aliquet. Integer quis auctor mi, in condimentum eros. In eleifend, lacus vel suscipit facilisis, felis libero consequat mi, commodo porta tellus mi eu neque. Fusce in elit sed sapien pulvinar dictum. Pellentesque nec aliquam diam, eget suscipit leo. Curabitur eleifend augue vitae libero tincidunt sagittis. Pellentesque vestibulum nec sapien quis rutrum. Mauris erat ex, ullamcorper a tortor vitae, iaculis tincidunt mauris. Ut in diam orci. In et neque imperdiet, gravida odio in, dictum odio.');
INSERT INTO Articles ("id", "uuid", "hfso", "title", "image", "text") VALUES (3, '66f30199-86f1-483c-b8fd-d1bf057ac6b2', 'F', 'Food Article', 'Content/Images/articles/food1.jpg', 'Food article vivamus sed quam id ligula dictum posuere sed eget turpis. Suspendisse a metus at purus scelerisque condimentum eu vitae urna. Etiam sit amet viverra quam. Sed sagittis, dolor in cursus placerat, ex lacus faucibus erat, at imperdiet eros orci ac arcu. Pellentesque velit libero, bibendum ut dictum ac, pellentesque quis quam. Nam feugiat vel risus et fringilla. Vestibulum commodo arcu sem. Vivamus vel nisi lorem. Donec in cursus lorem, pellentesque porttitor dui. Cras sollicitudin metus nec euismod tempor. Pellentesque maximus, dui sit amet rutrum sagittis, mi sem maximus dui, eget consequat augue diam et nisi. Mauris accumsan libero in velit vestibulum, non scelerisque diam tristique. Morbi id congue mi, sit amet ullamcorper est.');
INSERT INTO Articles ("id", "uuid", "hfso", "title", "image", "text") VALUES (4, '11084cf1-5abf-49e7-87f9-2c4a5d6f04ff', 'T', 'British Flag', 'Content/Images/articles/british_flag.png', 'British flag duis vitae interdum ex, in suscipit lacus. Sed mollis est scelerisque purus dapibus aliquam. Donec a elit ut urna pulvinar sollicitudin. Fusce et purus eget nisi vestibulum laoreet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus arcu mi, condimentum id lacinia sollicitudin, maximus ac lacus. Vestibulum vehicula vestibulum magna, tempor pretium sapien sagittis sit amet. Fusce sollicitudin feugiat efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin bibendum nisi ac nisi faucibus, fringilla elementum libero auctor. Donec ornare, velit nec malesuada tincidunt, est enim lobortis felis, in posuere lorem felis in leo. Praesent porttitor, felis eu ultrices blandit, est urna sodales sem, quis aliquam sapien felis ac lacus. Mauris sed condimentum ante, ac sollicitudin justo.');
INSERT INTO Articles ("id", "uuid", "hfso", "title", "image", "text") VALUES (5, 'd6303779-dfd9-4e09-bd0f-37502265cafd', 'F', 'American Flag', 'Content/Images/articles/american_flag.png', 'American flag vestibulum sodales maximus tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sapien purus, aliquet iaculis augue congue, ornare mattis neque. Phasellus sit amet metus consequat, vulputate tortor nec, pretium mauris. In est nisi, dictum sit amet nunc vitae, egestas finibus dui. Curabitur dapibus, elit id interdum tincidunt, velit lacus gravida massa, et vestibulum arcu dui vel tortor. Quisque ornare cursus feugiat. Curabitur felis nunc, pellentesque ut augue eget, vestibulum commodo nisl. Cras imperdiet, lorem sed placerat eleifend, orci ipsum volutpat arcu, tristique dignissim turpis arcu ut turpis. Maecenas fermentum eros quis nulla tempor, sit amet scelerisque augue auctor. In posuere arcu at ante fringilla, imperdiet vehicula augue consectetur. Nam tincidunt volutpat lectus, blandit sagittis nunc mattis vitae. Aliquam non est justo. Vivamus interdum magna quis porttitor varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.');

DELETE FROM Feature;
INSERT INTO Feature ("id", "article", "image1", "image2", "image3", "title") VALUES (1, 'This is feature text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet ipsum id velit dapibus maximus. Maecenas non felis interdum, efficitur justo ut, maximus felis. \r\n\r\nUt mauris lorem, gravida vel metus et, pulvinar malesuada erat. Sed sem ex, ullamcorper id ornare eu, imperdiet faucibus nunc. Sed nec lobortis nunc, eu porta orci. \r\n\r\nDonec eget dignissim odio, ut sagittis neque. Pellentesque pharetra volutpat maximus. ', 'Content/Images/feature/construction1.jpg', 'Content/Images/feature/construction2.jpg', 'Content/Images/feature/construction3.jpg', 'New Construction in Deer Park');

DELETE FROM Officers;
INSERT INTO Officers ("id", "name", "email", "description", "photo") VALUES (1, 'Stephen Dyer', 'stephen.dyer@dpnatest.com', 'co-President', 'Content/Images/officers/Stephen_Dyer.jpg');
INSERT INTO Officers ("id", "name", "email", "description", "photo") VALUES (2, 'Anthony Short', 'anthony.short@dpnatest.com', 'co-President', 'Content/Images/officers/Anthony_Short.jpg');
INSERT INTO Officers ("id", "name", "email", "description", "photo") VALUES (3, 'Victoria Coleman', 'victoria.coleman@dpnatest.com', 'Treasurer', 'Content/Images/officers/Victoria_Coleman.jpg');
INSERT INTO Officers ("id", "name", "email", "description", "photo") VALUES (4, 'Luke Vaughan', 'luke.vaughan@dpnatest.com', 'Secretary', 'Content/Images/officers/Luke_Vaughan.jpg');
INSERT INTO Officers ("id", "name", "email", "description", "photo") VALUES (5, 'Gabrielle Metcalfe', 'gabrielle.metcalfe@dpnatest.com', 'Board Member', 'img/officers/Gabrielle_Metcalf.jpg');
INSERT INTO Officers ("id", "name", "email", "description", "photo") VALUES (6, 'Penelope Mitchell', 'penelope.mitchell@dpnatest.com', 'Board Member', 'Content/Images/officers/Penelope_Mitchell.jpg');
INSERT INTO Officers ("id", "name", "email", "description", "photo") VALUES (7, 'David Ferguson', 'david.ferguson@dpnatest.com', 'Board Member', 'Content/Images/officers/David_Ferguson.jpg');
INSERT INTO Officers ("id", "name", "email", "description", "photo") VALUES (8, 'Eric Kerr', 'eric.kerr@dpnatest.com', 'Board Member', 'Content/Images/officers/Eric_Kerr.jpg');
INSERT INTO Officers ("id", "name", "email", "description", "photo") VALUES (9, 'Dorothy Martin', 'dorothy.martin@dpnatest.com', 'Board Member', 'Content/Images/officers/Dorothy_Martin.jpg');
INSERT INTO Officers ("id", "name", "email", "description", "photo") VALUES (10, 'Carolyn Underwood', 'carolyn.underwood@dpnatest.com', 'Board Member', 'Content/Images/officers/Carolyn_Underwood.jpg');

DELETE FROM Services;
INSERT INTO Services ("id", "text") VALUES (1, 'Emergencies: 911');
INSERT INTO Services ("id", "text") VALUES (2, 'City Call (non-emergency): 311 or 555-2221');
INSERT INTO Services ("id", "text") VALUES (3, 'Police, DP district (non-emergency): 555-1212');
INSERT INTO Services ("id", "text") VALUES (4, 'Metro Council Member''s Office: 555-2211');
INSERT INTO Services ("id", "text") VALUES (5, 'Mayor''s Office: 555-1122');
INSERT INTO Services ("id", "text") VALUES (6, 'School Board: 555-1112');

DELETE FROM Videos;
INSERT INTO Videos ("id", "site", "type", "title", "description", "link") VALUES (1, 'onsite', 'video/ogg', 'Natural Gas', 'Large quantities of natural gas discovered in Deer Park neighborhood!', 'Content/Videos/Natural_Gas_video.ogg');
INSERT INTO Videos ("id", "site", "type", "title", "description", "link") VALUES (2, 'youtube', '', 'Pinback: A Request', 'From the album ''Information Received''.', 'https://www.youtube.com/watch?v=MaHrMR7JRS8');
INSERT INTO Videos ("id", "site", "type", "title", "description", "link") VALUES (3, '', '', 'No video', 'Sorry, there is no video available.', 'Content/Images/no_cat.jpg');
INSERT INTO Videos ("id", "site", "type", "title", "description", "link") VALUES (4, 'youtube', '', 'Dave''s World: He Gooched His Bass Guitar', 'Dave fixes a bass and enjoys a beer.', 'https://www.youtube.com/watch?v=EZ10jbzcD18');
INSERT INTO Videos ("id", "site", "type", "title", "description", "link") VALUES (5, 'youtube', '', 'You Only Live Once (Cover)', 'Five dudes, who look remarkably alike, cover The Strokes.', 'https://www.youtube.com/watch?v=GLf3nrZXZT8');
